api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "chicya-delivery"
type = "function"
uid = "79591a7e-0199-06fa-a514-07a6dda9163e6e6a2e38"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.delivery-options.transform.run"
  input_query = "src/cart_delivery_options_transform_run.graphql"
  export = "cart_delivery_options_transform_run"

  [extensions.build]
  command = "cargo build --target=wasm32-unknown-unknown --release"
  path = "target/wasm32-unknown-unknown/release/chicya-delivery.wasm"
  watch = [ "src/**/*.rs" ]

  [extensions.ui.paths]
  create = "/"
  details = "/"
