api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "chicya-checkout-validation"
type = "function"
uid = "d1ea512e09b04743958d98432d38610d"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.validations.generate.run"
  input_query = "src/checkout_validation_run.graphql"
  export = "checkout_validation_run"

  [extensions.build]
  command = "cargo build --target=wasm32-unknown-unknown --release"
  path = "target/wasm32-unknown-unknown/release/chicya-checkout-validation.wasm"
  watch = [ "src/**/*.rs" ]

  [extensions.ui.paths]
  create = "/"
  details = "/"