api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "chicya-cart-transform"
type = "function"
uid = "0867b9cd-802f-fac5-4fd9-6b4dbef2f1a5fb866f0a"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart_transform_run"

  [extensions.build]
  command = "cargo build --target=wasm32-unknown-unknown --release"
  path = "target/wasm32-unknown-unknown/release/chicya-cart-transform.wasm"
  watch = [ "src/**/*.rs" ]

  [extensions.ui.paths]
  create = "/"
  details = "/"
